### ISSUE TITLE
github pages

### ISSUE THREAD

**Issue by jwijffels** [IDDI-BE/PhIIdesign#2]
@kdhollander 
Can you enable github pages under settings > Github Pages 
![Knipsel](https://user-images.githubusercontent.com/1710810/85419381-4fec3200-b572-11ea-9214-21b730391949.PNG)
And make sure GitHub pages source is set to “gh-pages”
You are the owner of the repo, so you will have to do this
After that site should normally appear at https://iddi-be.github.com/PhIIdesign

**Comment by kdhollander** [comment]
Ik denk dat het gelukt is!

**Comment by jwijffels** [comment]
Thanks. Indeed works. Web app now runs at https://iddi-be.github.io/PhIIdesign/index.html
