### ISSUE TITLE
sargent2stage

### ISSUE THREAD

**Issue by jwijffels** [IDDI-BE/PhIIdesign#4]
@kdhollander
Voor sargent2 (https://github.com/IDDI-BE/PhIIdesign/blob/master/R/sargent2stage.R#L13) is de core functie 
```
probha <- function(n1, n2, r1, s, p) {
  i <- seq(r1 + 1, min(n1, s))
  sum(pbinom(q = s - i - 1, size = n2, prob = p, lower.tail = F) * dbinom(i, size = n1, prob = p)) +
    as.numeric(n1 > s) * pbinom(q = s, size = n1, prob = p, lower.tail = F)
}
```

Als ik die toepas op volgende setting lijkt me de code in probha niet correct, reden is dat in `pbinom(q = s - i - 1, size = n2, prob = p, lower.tail = F)`,` s - i - 1` negatief wordt... . Ik denk dat dit niet de bedoeling is als ik kijk naar de formule - kan je dat verifiëren. Ik merk dat dit gebeurt in 25% van de rijen wanneer sargent2stage  opgeroepen wordt.

```
> probha(n1 = 14, n2 = 7, r1 = 1, s = 5, p = 0.1)
[1] 0.05114121
> probha(n1 = 14, n2 = 7, r1 = 1, s = 5, p = 0.3)
[1] 0.7962944
```

**Comment by kdhollander** [comment]
Dag Jan,

De formule in Sargent (p122) vraagt: P(X2>=s-i)

Nu, de functie pbinom(q, size, prob, lower.tail = TRUE, log.p = FALSE) in R doet hetvolgende:


lower.tail=TRUE: P(X<=x|p) ofwel P(X<x+1)

lower.tail=FALSE:P(X>x|p) ofwel P(X>=x+1)


Dus voor Sargent: pbinom P(X2>s-i-1) of 1-P(X2<=s-i-1)

i kan inderdaad maximaal gelijk worden aan s, en dan krijg je:

P(X2>=0) ofwel P(X2>-1). Dus de minimum waarde zou -1 moeten zijn. En dit lijkt me geen probleem, want die kans is gewoon gelijk aan 1.

> pbinom(-1,20,0.5,lower.tail=F)
[1] 1
> 1-pbinom(-1,20,0.5,lower.tail=T)
[1] 1

Met andere woorden, ik denk dat je niets moet veranderen als de negatieve getallen die je krijgt, enkel -1 zijn. Indien nog kleinere getallen, is er iets mis 🙂

Groetjes,

Koenraad

________________________________

**Comment by kdhollander** [comment]
Hoi Koenraad,

Duidelijk overzicht, enkel 1 opmerking: als in de probha functie de som over probs genomen wordt, dan zal de onbestaande -1 waarde  een te hoge som geven (+1). In dit geval zal dan de 1-P(X2<=s-i-1) een juiste waarde berekenen en de pbinom P(X2>s-i-1) niet. Maar verder zoals je aangeeft geen verschillen tussen beiden, dus kan Jan de vervanging doen die hij voorstelt indien nodig.

Groetjes,
Els




________________________________

**Comment by jwijffels** [comment]
In de speedup wordt inderdaad `de som over de probs genomen` vandaar dat die berekening inderdaad andere resultaten gaf voor settings waar -1 voorkwam.

**Comment by kdhollander** [comment]
de prob=1 zit in een vermenigvuldiging, dus normaal zou dat geen probabilities>1 mogen geven.
Volgens mij moet er niets veranderen, en is de -1 dus geen probleem.
Zie je daar nog problemen mee, Jan?
Groetjes


________________________________

**Comment by jwijffels** [comment]
Heb de sargent2stage aangepast en volgende logica gebruikt omdat dit makkelijker is in de speedup die ik geimplementeerd had.

``` r
probha <- function(n1, n2, r1, s, p, type = "original") {
  ## Equation 4 page 122 Sargent et. Al
  i <- seq(r1 + 1, min(n1, s))
  if(type == "original"){
    pbinom(q = s, size = n1, prob = p, lower.tail = FALSE) * as.numeric(n1 > s) +
      sum(pbinom(q = s - i - 1, size = n2, prob = p, lower.tail = FALSE) * dbinom(i, size = n1, prob = p))
  }else if(type == "speedup"){
    pbinom(q = s, size = n1, prob = p, lower.tail = FALSE) * as.numeric(n1 > s) +
      sum((1 - pbinom(q = s - i, size = n2, prob = p, lower.tail = TRUE) + dbinom(s - i, size = n2, prob = p)) * dbinom(i, size = n1, prob = p))
  }
}
probha(n1 = 14, n2 = 7, r1 = 1, s = 5, p = 0.1, type = "original")
#> [1] 0.05114121
probha(n1 = 14, n2 = 7, r1 = 1, s = 5, p = 0.1, type = "speedup")
#> [1] 0.05114121
```

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jwijffels** [comment]
@kdhollander 
@ecoart72 
Ik heb de speedup van sargent2 gepusht in commit https://github.com/IDDI-BE/PhIIdesign/commit/3dadd7f79306416c90e4413c34a5ea9f06784846
Is net zoals simon2 4x sneller dan wat origineel er stond.

**Comment by jwijffels** [comment]
Ga dit sluiten. Is opgelost ondertussen.
