### ISSUE TITLE
app

### ISSUE THREAD

**Issue by jwijffels** [IDDI-BE/PhIIdesign#6]
@ecoart72 
@kdhollander
Ik dacht aan volgende design qua shiny app. Misschien kunnen jullie al feedback geven. Grafieken en tabellen zijn nog fake, gaat mij om de layout. 
Bedoeling is als er op de knop gedrukt wordt een popup te tonen met mogelijke inputs van het design.

![Knipsel](https://user-images.githubusercontent.com/1710810/95717247-f3ba3480-0c6c-11eb-98b9-31b2cefaebe1.PNG)

**Comment by kdhollander** [comment]
Hoi Jan, bij de parameters moet zeker een woordje uitleg staan, of een link naar uitleg. In ieder geval iets dat zeer snel toegankelijk is, en waarvoor je niet de documentation voor moet doorscrollen.

**Comment by jwijffels** [comment]
@kdhollander 
@ecoart72
Ik heb de app geupdate. Kijken jullie even wat graag nog aangepast moet worden.

![Video_20-10-23_09-23-12](https://user-images.githubusercontent.com/1710810/96969369-b712f680-1512-11eb-960c-ebe09953303a.gif)
